runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v1 
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        platforms: linux/amd64
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.registry }}/${{ inputs.github_repo }}/${{ inputs.image }}:${{ inputs.matlab_release }}
        build-args: MATLAB_RELEASE=${{ inputs.matlab_release }}
        push: true

